docs: Updated go install command
aws-cloudformation/rain pull request #219
Opened 2023-12-05 14:55 UTC by khmoryz

**No issue**

**Description of changes**
## Change 1

Add`@latest`to end of line.

Reason:

```sh
docker pull golang:latest
docker run -it --rm golang:latest /bin/bash
root@534e3854e96c:/go# GO111MODULE=on go install github.com/aws-cloudformation/rain/cmd/rain
go: 'go install' requires a version when current directory is not in a module
        Try 'go install github.com/aws-cloudformation/rain/cmd/rain@latest' to install the latest version
```

## Change 2

After go1.17, `GO111MODULE` is ignored.

https://go.dev/blog/go116-module-changes

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-12-05 17:19 UTC, ericzbeard requested changes

2023-12-06 18:07 UTC, ericzbeard commented on README.md
> +Or if you're a [Gopher](https://blog.golang.org/gopher), you can `go install github.com/aws-cloudformation/rain/cmd/rain@latest`
Run `go generate ./...` and then push another commit with the generated files.

2023-12-07 11:33 UTC, khmoryz commented on README.md
> +Or if you're a [Gopher](https://blog.golang.org/gopher), you can `go install github.com/aws-cloudformation/rain/cmd/rain@latest`
I did it at https://github.com/aws-cloudformation/rain/pull/219/commits/29e548ee8754bf0c612f54abc34c917566953f96.

And...
I noticed cfn.go is updated.
This automation is awesome!

2023-12-07 15:12 UTC, ericzbeard approved these changes

2023-12-07 15:12 UTC, merged