Add support for Claude3-Opus
aws-cloudformation/rain pull request #374
Opened 2024-04-25 12:22 UTC by watany-dev

*Issue #, if available:*

https://github.com/aws-cloudformation/rain/issues/368

*Description of changes:*

model-id's below.

https://aws.amazon.com/jp/blogs/aws/anthropics-claude-3-opus-model-on-amazon-bedrock/

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-04-25 14:43 UTC, ericzbeard approved these changes

2024-04-25 14:46 UTC, ericzbeard commented
Linter check is failing:
```
Run staticcheck ./...
-: # github.com/aws-cloudformation/rain/internal/cmd/build
internal/cmd/build/interactive.go:106:11: undefined: OPUS (compile)
-: # github.com/aws-cloudformation/rain/internal/cmd/build [github.com/aws-cloudformation/rain/internal/cmd/build.test]
internal/cmd/build/interactive.go:106:11: undefined: OPUS (compile)
Error: Process completed with exit code 1.
```

2024-04-25 14:46 UTC, ericzbeard requested changes
Should be a simple fix for the linter error, then I'll merge it.

2024-04-26 04:09 UTC, watany-dev commented
@ericzbeard 
I'm sorry. I tried to fix it.

2024-04-26 15:39 UTC, ericzbeard approved these changes

2024-04-26 15:39 UTC, merged